platform: vertexai
vertexai:
    project_id: &project wmt-mtech-assortment-ml-prod
element:
    bigquery:
        connector: gcp-mtech-dev
models:
    endpoint: &endpoint !concat ['https://us-central1-aiplatform.googleapis.com/v1/projects/',*project,'/locations/us-central1/publishers/google/models/']
    llm: 
        name: &llm gemini-1.5-pro-001
        gateway_url: !concat [*endpoint,*llm,':generateContent']
        generation_config:
            maxOutputTokens: 2048
            temperature: 0
            topP: 1
    embedding:
        name: &embedding text-embedding-004
        gateway_url: !concat [*endpoint,*embedding,':predict']
knowledge:
    documents:
        metrics: !read_csv 'resources/metrics.csv'
    db:
        path: 'resources/db/vector/'
bigquery:
    mapping:
        table_id: wmt-mtech-assortment-ml-dev.clearance_markdown_ml_dev.plan_dept_sbu_mapping
        description: !read_text 'resources/mapping/plan_dept_sbu_mapping.txt'
        schema: !read_csv 'resources/mapping/mapping.csv'
        primary_key: [plan_id]
    apparel:
        table_id: wmt-mtech-assortment-ml-prod.clearance_md_report.apparel_cmd_wkly_kpi_table_rpt
        description: !read_text 'resources/apparel/apparel_weekly_report.txt'
        schema: !read_csv 'resources/apparel/apparel_weekly_report.csv'
        primary_key: [plan_id, store_nbr, prime_item_nbr, WM_YEAR_WK_NBR]
    food: &fcgm
        table_id: wmt-mtech-assortment-ml-prod.clearance_md_report.fcgm_cmd_wkly_kpi_table_rpt
        description: !read_text 'resources/fcgm/fcgm_weekly_report.txt'
        schema: !read_csv 'resources/fcgm/fcgm_weekly_report.csv'
        primary_key: [plan_id, store_nbr, prime_item_nbr, WM_YEAR_WK_NBR]
    cons: *fcgm
    hardlines: *fcgm
    home: *fcgm
    ets: *fcgm
